### ISSUE TITLE
not receiving confirmation code

### ISSUE THREAD

**Issue by jpcrumley** [julianfez/homebridge-augustlock2#3]
I've got the plugin running.  I'm using Hesperus to do the initial setup.  I'm putting in my number with 1 in front of the area code but not including the + but I'm never getting a confirmation code back.

**Comment by JAEberhart** [comment]
I'm in same boat.

Does this work for 1st gen August Locks too?

I've added this to config.json . . .

{
          "platform": "AugustLock2",
          "phone": "<1+phone number>",
          "password": "<August Account Password>",
          "securityToken": "<still havn't received text token.>"
}

**Comment by LazzR1** [comment]
Was there ever a fix for this? I've tried everything and never get the confirmation code text. I'd really love to get this working.

**Comment by kaaneroglu** [comment]
ho do you request the security token? Also, where did you find that config json for this plugin?

**Comment by bryangauvin** [comment]
What am I doing wrong here?  No text, no email being received with token

Code in Json
{
            "platform": "AugustLock2",
            "phone": "14075555555",
            "email": "XXXXXX@gmail.com",
            "password": "XXXXX",
            "installId": "b7e2efe6-4r3e-11e7-9296-ce8278b6c50a"
        },

Terminal Messages
[2018-12-16 10:51:26] [AugustLock2] [August] Logged in with ID 08e7f40d-5234-4815-94a6-961d3abcf366
[2018-12-16 10:51:26] [AugustLock2] [August] getting locks ...
[2018-12-16 10:51:26] [AugustLock2] [August] Error: Http error: 401
    at Request._callback (C:\Users\Bryan\AppData\Roaming\npm\node_modules\homebridge-augustlock\api.js:29:35)
    at Request.self.callback (C:\Users\Bryan\AppData\Roaming\npm\node_modules\homebridge-augustlock\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Bryan\AppData\Roaming\npm\node_modules\homebridge-augustlock\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Bryan\AppData\Roaming\npm\node_modules\homebridge-augustlock\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
